### ISSUE TITLE
Consolidated zoning categories

### ISSUE THREAD

**Issue by tiernanmartin** [zoningspace/zoning.space#18]
Exciting project!

Have you considered implementing a unified classification scheme for the different types of zoning? It can be useful for generating summary statistics and modeling.

For example, King County, Washington uses the following 20-class system in its [county-wide zoning data](http://www5.kingcounty.gov/sdc/Metadata.aspx?Layer=zoning_kc_consol_20):

|CATEGORY                            |
|:-----------------------------------|
|Single-Family Residential           |
|Rural Area                          |
|General Mixed Use                   |
|General Commercial                  |
|Multi-Family Residential            |
|Industrial/Manufacturing            |
|Agriculture-Related                 |
|Central Business District           |
|Office/Business Park                |
|Mixed Use Commercial/Residential    |
|Undesignated                        |
|Mixed Use Commercial/Office         |
|Public Use/Institutional            |
|Forest                              |
|Park/Golf Course/Trail/Open Space   |
|Aviation and Transportation-Related |
|Mobile Home Park                    |
|Historic District                   |
|Mineral Resource-Related            |
|Sensitive/Critical Area             |

**Comment by mattwigway** [comment]
It's not something we've considered; the main point of the zoning.space project is to get highly specific rather than generalized information, and I'm not sure how easy it would be to build a generalized taxonomy for zoning across the whole country. Implementing a generalized classification system on top of our detailed data should be possible (although for some of the classifications you list above we might need to record a little more information).

We also are currently focusing only on residential, but we're more than open to proposals to expand the schema to encompass commercial.

Thanks for your interest in zoning.space!

**Comment by tiernanmartin** [comment]
Got it 👍
